.TH "test/Product Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Product Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProductTest\&.cpp\fP"
.br
.RI "Source file of tests for the \fBProduct\fP class\&. "
.in -1c
