.TH "src/SalesReport Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SalesReport Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSalesReport\&.cpp\fP"
.br
.RI "Source file for the \fBSalesReport\fP class\&. "
.ti -1c
.RI "file \fBSalesReport\&.h\fP"
.br
.RI "Header file for the \fBSalesReport\fP class\&. "
.in -1c
