.TH "src Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEvent\fP"
.br
.ti -1c
.RI "directory \fBgui\fP"
.br
.ti -1c
.RI "directory \fBProduct\fP"
.br
.ti -1c
.RI "directory \fBReport\fP"
.br
.ti -1c
.RI "directory \fBSalesReport\fP"
.br
.ti -1c
.RI "directory \fBSimulation\fP"
.br
.ti -1c
.RI "directory \fBStorage\fP"
.br
.ti -1c
.RI "directory \fBWarehouse\fP"
.br
.ti -1c
.RI "directory \fBWarehouseReport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "Main entry point for the \fBWarehouse\fP Simulator application\&. "
.in -1c
