.TH "src/Event Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Event Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEvent\&.cpp\fP"
.br
.RI "Source file of the \fBEvent\fP class\&. "
.ti -1c
.RI "file \fBEvent\&.h\fP"
.br
.RI "Header file of the \fBEvent\fP class\&. "
.in -1c
