.TH "src/gui Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgui\&.cpp\fP"
.br
.RI "Source file for the \fBGUI\fP class\&. "
.ti -1c
.RI "file \fBgui\&.h\fP"
.br
.RI "Header file for the \fBGUI\fP class\&. "
.in -1c
