.TH "src/Report Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Report Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBReport\&.cpp\fP"
.br
.RI "Source file for the \fBReport\fP class\&. "
.ti -1c
.RI "file \fBReport\&.h\fP"
.br
.RI "Header file for the \fBReport\fP class\&. "
.in -1c
