.TH "src/WarehouseReport Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WarehouseReport Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBWarehouseReport\&.cpp\fP"
.br
.RI "Source file of the \fBWarehouseReport\fP class\&. "
.ti -1c
.RI "file \fBWarehouseReport\&.h\fP"
.br
.RI "Header file of the \fBWarehouseReport\fP class\&. "
.in -1c
