.TH "src/Storage Directory Reference" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Storage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBStorage\&.cpp\fP"
.br
.RI "Source file of the \fBStorage\fP class\&. "
.ti -1c
.RI "file \fBStorage\&.h\fP"
.br
.RI "Header file of the \fBStorage\fP class\&. "
.in -1c
