.TH "test/Event/EventTest.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Event/EventTest.cpp \- Source file of tests for the \fBEvent\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include 'Event/Event\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (EventTest, itLives)"
.br
.RI "Test to ensure that a \fBEvent\fP object can be instantiated\&. "
.ti -1c
.RI "\fBTEST\fP (EventTest, generateEventShouldReturnCorrectValue)"
.br
.RI "Test to verify that the method generates a valid event\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of tests for the \fBEvent\fP class\&. 


.PP
Definition in file \fBEventTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (EventTest, generateEventShouldReturnCorrectValue)"

.PP
Test to verify that the method generates a valid event\&. 
.PP
Definition at line \fB20\fP of file \fBEventTest\&.cpp\fP\&.
.SS "TEST (EventTest, itLives)"

.PP
Test to ensure that a \fBEvent\fP object can be instantiated\&. 
.PP
Definition at line \fB12\fP of file \fBEventTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
