.TH "src/Event/Event.h" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Event/Event.h \- Header file of the \fBEvent\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <QDateTime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEvent\fP"
.br
.RI "The \fBEvent\fP class represents an event in the warehouse simulation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file of the \fBEvent\fP class\&. 


.PP
Definition in file \fBEvent\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
