.TH "src/gui/gui.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui/gui.cpp \- Source file for the \fBGUI\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'gui\&.h'\fP
.br
\fR#include '\&./ui_gui\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file for the \fBGUI\fP class\&. 


.PP
Definition in file \fBgui\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
