.TH "src/Product/Product.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Product/Product.cpp \- Source file for the \fBProduct\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Product\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file for the \fBProduct\fP class\&. 


.PP
Definition in file \fBProduct\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
