.TH "Report::ProductReport" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Report::ProductReport \- Represents a report for a single product\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Report\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the product\&. "
.ti -1c
.RI "\fBdouble\fP \fBprice\fP"
.br
.RI "Price of the product\&. "
.ti -1c
.RI "int \fBquantity\fP"
.br
.RI "Quantity of the product\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a report for a single product\&. 

This structure holds the details of a product for reporting purposes, including its name, price, and quantity\&. 
.PP
Definition at line \fB31\fP of file \fBReport\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP Report::ProductReport::name"

.PP
Name of the product\&. 
.PP
Definition at line \fB33\fP of file \fBReport\&.h\fP\&.
.SS "\fBdouble\fP Report::ProductReport::price"

.PP
Price of the product\&. 
.PP
Definition at line \fB34\fP of file \fBReport\&.h\fP\&.
.SS "int Report::ProductReport::quantity"

.PP
Quantity of the product\&. 
.PP
Definition at line \fB35\fP of file \fBReport\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
