.TH "test/Report/ReportTest.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Report/ReportTest.cpp \- Source file of tests for the \fBReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include 'Report/Report\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (ReportTest, generateReportShouldReturnNonEmptyString)"
.br
.RI "Test to ensure that the generateReport method does not return an empty string\&. "
.ti -1c
.RI "\fBTEST\fP (ReportTest, GenerateReportShouldReturnExpectedFormat)"
.br
.RI "Test to ensure that the generateReport method returns a string in the expected format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of tests for the \fBReport\fP class\&. 


.PP
Definition in file \fBReportTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (ReportTest, GenerateReportShouldReturnExpectedFormat)"

.PP
Test to ensure that the generateReport method returns a string in the expected format\&. 
.PP
Definition at line \fB24\fP of file \fBReportTest\&.cpp\fP\&.
.SS "TEST (ReportTest, generateReportShouldReturnNonEmptyString)"

.PP
Test to ensure that the generateReport method does not return an empty string\&. 
.PP
Definition at line \fB12\fP of file \fBReportTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
