.TH "src/Report/Report.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Report/Report.cpp \- Source file for the \fBReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Report\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file for the \fBReport\fP class\&. 


.PP
Definition in file \fBReport\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
