.TH "src/SalesReport/SalesReport.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SalesReport/SalesReport.cpp \- Source file for the \fBSalesReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'SalesReport\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file for the \fBSalesReport\fP class\&. 


.PP
Definition in file \fBSalesReport\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
