.TH "test/SalesReport/SalesReportTest.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/SalesReport/SalesReportTest.cpp \- Source file of tests for the \fBSalesReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include 'SalesReport/SalesReport\&.h'\fP
.br
\fR#include <QDateTime>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (SalesReportTest, itLives)"
.br
.RI "Test case to ensure that a \fBSalesReport\fP object can be instantiated\&. "
.ti -1c
.RI "\fBTEST\fP (SalesReportTest, generateReportShouldReturnCorrectValue)"
.br
.RI "Test case to verify that the \fBSalesReport::generateReport\fP method returns the correct CSV format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of tests for the \fBSalesReport\fP class\&. 


.PP
Definition in file \fBSalesReportTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (SalesReportTest, generateReportShouldReturnCorrectValue)"

.PP
Test case to verify that the \fBSalesReport::generateReport\fP method returns the correct CSV format\&. 
.PP
Definition at line \fB27\fP of file \fBSalesReportTest\&.cpp\fP\&.
.SS "TEST (SalesReportTest, itLives)"

.PP
Test case to ensure that a \fBSalesReport\fP object can be instantiated\&. 
.PP
Definition at line \fB13\fP of file \fBSalesReportTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
