.TH "src/Simulation/Simulation.h" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Simulation/Simulation.h \- Header file for the \fBSimulation\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <Warehouse/Warehouse\&.h>\fP
.br
\fR#include <WarehouseReport/WarehouseReport\&.h>\fP
.br
\fR#include <SalesReport/SalesReport\&.h>\fP
.br
\fR#include <Event/Event\&.h>\fP
.br
\fR#include <QList>\fP
.br
\fR#include <QDateTime>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QRandomGenerator>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulation\fP"
.br
.RI "The \fBSimulation\fP class manages the overall department store simulation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBSimulation\fP class\&. 

Declares the \fBSimulation\fP class and its members, which are responsible for managing the overall department store simulation\&. 
.PP
Definition in file \fBSimulation\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
