.TH "test/Simulation/SimulationTest.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Simulation/SimulationTest.cpp \- Source file of tests for the \fBSimulation\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include 'Simulation/Simulation\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (SimulationTest, itLives)"
.br
.RI "Test to ensure that the constructor initializes the current time correctly\&. "
.ti -1c
.RI "\fBTEST\fP (SimulationTest, processEvents)"
.br
.RI "Test to validate the processEvents method\&. "
.ti -1c
.RI "\fBTEST\fP (SimulationTest, conductCycle)"
.br
.RI "Test to check if the conductCycle method processes the simulation cycle successfully\&. "
.ti -1c
.RI "\fBTEST\fP (SimulationTest, generateReport)"
.br
.RI "Test to ensure that the generateReport method produces a report\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of tests for the \fBSimulation\fP class\&. 


.PP
Definition in file \fBSimulationTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (SimulationTest, conductCycle)"

.PP
Test to check if the conductCycle method processes the simulation cycle successfully\&. 
.PP
Definition at line \fB29\fP of file \fBSimulationTest\&.cpp\fP\&.
.SS "TEST (SimulationTest, generateReport)"

.PP
Test to ensure that the generateReport method produces a report\&. 
.PP
Definition at line \fB39\fP of file \fBSimulationTest\&.cpp\fP\&.
.SS "TEST (SimulationTest, itLives)"

.PP
Test to ensure that the constructor initializes the current time correctly\&. 
.PP
Definition at line \fB12\fP of file \fBSimulationTest\&.cpp\fP\&.
.SS "TEST (SimulationTest, processEvents)"

.PP
Test to validate the processEvents method\&. 
.PP
Definition at line \fB20\fP of file \fBSimulationTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
