.TH "src/Storage/Storage.h" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Storage/Storage.h \- Header file of the \fBStorage\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStorage\fP"
.br
.RI "The \fBStorage\fP class represents a storage unit with a certain capacity\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstorageStatus\fP { \fBEMPTY\fP, \fBAVAILABLE\fP, \fBFULLY\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file of the \fBStorage\fP class\&. 


.PP
Definition in file \fBStorage\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstorageStatus\fP"
Enum representing the status of the \fBStorage\fP capacity\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEMPTY \fP\fP
.TP
\fB\fIAVAILABLE \fP\fP
.TP
\fB\fIFULLY \fP\fP
.PP
Definition at line \fB10\fP of file \fBStorage\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
