.TH "src/Storage/Storage.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Storage/Storage.cpp \- Source file of the \fBStorage\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Storage\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file of the \fBStorage\fP class\&. 


.PP
Definition in file \fBStorage\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
