.TH "test/WarehouseReport/WarehouseReportTest.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/WarehouseReport/WarehouseReportTest.cpp \- Source file of tests for the \fBWarehouseReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br
\fR#include 'WarehouseReport/WarehouseReport\&.h'\fP
.br
\fR#include <QDateTime>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (WarehouseReportTest, itLives)"
.br
.RI "Test case to ensure that a \fBWarehouseReport\fP object can be instantiated\&. "
.ti -1c
.RI "\fBTEST\fP (WarehouseReportTest, generateReportShouldReturnCorrectValue)"
.br
.RI "Test case to verify that the \fBWarehouseReport::generateReport\fP method returns the correct CSV format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of tests for the \fBWarehouseReport\fP class\&. 


.PP
Definition in file \fBWarehouseReportTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (WarehouseReportTest, generateReportShouldReturnCorrectValue)"

.PP
Test case to verify that the \fBWarehouseReport::generateReport\fP method returns the correct CSV format\&. 
.PP
Definition at line \fB27\fP of file \fBWarehouseReportTest\&.cpp\fP\&.
.SS "TEST (WarehouseReportTest, itLives)"

.PP
Test case to ensure that a \fBWarehouseReport\fP object can be instantiated\&. 
.PP
Definition at line \fB13\fP of file \fBWarehouseReportTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
