.TH "src/WarehouseReport/WarehouseReport.cpp" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WarehouseReport/WarehouseReport.cpp \- Source file of the \fBWarehouseReport\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'WarehouseReport\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Source file of the \fBWarehouseReport\fP class\&. 


.PP
Definition in file \fBWarehouseReport\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
