.TH "src/Warehouse/Warehouse.h" 3 "Version 1.0.0" "Warehouse Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Warehouse/Warehouse.h \- Source file of the \fBWarehouse\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Storage/Storage\&.h'\fP
.br
\fR#include 'Product/Product\&.h'\fP
.br
\fR#include <QList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWarehouse\fP"
.br
.RI "The \fBWarehouse\fP class represents a warehouse with storage capacity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Source file of the \fBWarehouse\fP class\&. 

Header file of the \fBWarehouse\fP class\&.
.PP
Definition in file \fBWarehouse\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Warehouse Simulator from the source code\&.
